### ISSUE TITLE
Indicators: how to hide or add custom styles?

### ISSUE THREAD

**Issue by Yaroslav-Pryadunov** [Hejtmus/svelte-fullpage#20]

**Comment by Hejtmus** [comment]
Hi,

Thank you for using this lib.

For styling fullpage components you can use **style** or **class** property (for **any fullpage component**).
If you want to remove default style, you can just override it.

Here is link to [tweaks](https://github.com/Hejtmus/svelte-fullpage#tweaks) section in documentation.

Best regards.
