### ISSUE TITLE
Page reloads on mobile 

### ISSUE THREAD

**Issue by gevera** [Hejtmus/svelte-fullpage#21]
When on mobile and try to go back up by swiping page reloads

**Comment by Hejtmus** [comment]
# Feature you suggested has been implemented

so prevention from pull down to refresh is disabled now by default.

Try to update to the latest version (0.2.10) and please confirm that it works (or it doesn't, in that case, it would be better to provide me with more info, so I can fix it).

**Comment by Hejtmus** [comment]
No response, closing this issue.

I have tested this newly added feature, everything works (at least for me).
If you can't give me feedback and you find out this feature doesn't work, reopen this issue.

Bye and thank you for your contribution with idea.
