### ISSUE TITLE
The scroll event doesn't work properly on an iPhone using Safari

### ISSUE THREAD

**Issue by simonSlamka** [Hejtmus/svelte-fullpage#38]
**Describe the bug**
When using Safari on an iPhone, the transition between views when attempting to scroll seems broken. In contrast, it appears to be working correctly when using Firefox under Windows, so the issue is likely in Safari.

**To Reproduce**
1. Use Safari on an iPhone to navigate to [https://hejtmus.github.io/svelte-fullpage/](https://hejtmus.github.io/svelte-fullpage/)
2. Press the dots to the right to "scroll" to the following view
3. Witness the broken transition

**Expected behavior**
The transition should be smooth and clean, like when using Firefox on a desktop.

**Screenshots**
Got a screencap from an iPhone 12.
URL: [https://simtoonia.ongakken.com/s/WwHmt3afPLwANRp](https://simtoonia.ongakken.com/s/WwHmt3afPLwANRp)
Passwd: `eAi38@!85hga3@(#jkf`

**Smartphone (please complete the following information):**
- Device: Apple iPhone 12
- OS: Apple iOS 16 (20A362)
- Browser: Safari

**Additional context**
The "swipe" event doesn't work at all. This issue appears when pressing the dots on the right side to advance to another view.

**Comment by Hejtmus** [comment]
Hey,

thank you for your report. I have analyzed the bug and its fix will be featured within new major version (1.0.0).

Best regards,
Filip.

**Comment by simonSlamka** [comment]
> Hey,
> 
> thank you for your report. I have analyzed the bug and its fix will be featured within new major version (1.0.0).
> 
> Best regards, Filip.

Great, looking forward to it!

**Comment by Hejtmus** [comment]
Hey, I have finished huge update, could you please test new demo page on your device?

**Comment by simonSlamka** [comment]
> Hey @simonSlamka, I have finished huge update, could you please test new demo page on your device?

Sure, but I'm not sure about keeping updated about this or other issues on GitHub. I have an ongoing issue with them that made me leave for a FOSS solution instead.
https://github.com/simonSlamka/simonSlamka#readme

**Comment by simonSlamka** [comment]
My hardened Firefox 105.0.3 running under Arch doesn't display the background colors and the little dots on the right are not getting highlighted.

Back in Safari, the scrolling is now functional and seems to be behaving as one might expect. Those "dots" on the right are a bit stretched to the sides and look like ovals, but otherwise, all good. Even the side scroll works.

**Comment by Hejtmus** [comment]
I'm glad to see that, than you for your feedback. I may consider mirroring this (and other repos) on FOSS GitHub alternative.
