### ISSUE TITLE
FullPageSlide scrolls down on mobile when tapped

### ISSUE THREAD

**Issue by Siutan** [Hejtmus/svelte-fullpage#58]
**Describe the bug**
FullPageSlide scrolls down when user taps anywhere on screen. Only happens on mobile.

**To Reproduce**
1. Add FullPageSlide section
2. Access on mobile
3. Tap anywhere
4. See scroll effect

**Expected behavior**
Nothing should happen.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g.Edge]
 - Version [e.g. 115.0.1901.203]

**Smartphone (please complete the following information):**
 - Device: [e.g. Samasung Galaxy Fold 4]
 - OS: [e.g. Android 13]
 - Browser [e.g. Chrome]
 - Version [e.g. 115.0.5790.166]

**Comment by Hejtmus** [comment]
Hey @Siutan,

thanks for report, I successfully reproduced your bug, I will try to fix it ASAP, I hope I can get to it until end of this week.
If you need it sooner and you are willing to fix it, feel free to make PR.

Best regards,
Filip.
